---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  arg-workflows-helm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/buildstar-online/argocd-apps.git
    path: apps/argo-workflows/
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
